version: '2'
services:
  postgres:
    image: postgres:9.6.1
    container_name: mega_postgres
    volumes:
      - ./.data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: mega
      POSTGRES_PASSWORD: mega
      POSTGRES_DB: mega
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: mega_app
    ports:
      - "80:3000"
    links:
      - postgres:postgres
    volumes:
      - ./webpack.config.js:/app/webpack.config.js
      - ./src:/app/src
    environment:
      - NODE_ENV=development
      - MAILGUN_USERNAME
      - MAILGUN_PASSWORD
      - DB_HOST
      - DB_USER
      - DB_PASSWORD
      - DB_NAME
      - TOKEN_SECRET
      - GOOGLE_SECRET
      - GITHUB_SECRET